/**
 * og-worker.js — Aesop AI Academy OG Tag Injector
 *
 * Intercepts requests to electives-hub.html?course=<id> and rewrites
 * the Open Graph / Twitter Card meta tags to be course-specific, so
 * that pasting a course link in LinkedIn, Slack, iMessage, etc. shows
 * the correct course title, description, and OG image.
 *
 * Deploy route: aesopacademy.org/ai-academy/modules/electives-hub.html*
 *
 * The Worker never needs updating when new courses launch — it reads
 * courses-data.json at runtime and constructs the OG image URL from
 * the course ID. The OG images themselves are generated automatically
 * by the generate-og-images GitHub Action.
 */

const ORIGIN       = 'https://aesopacademy.org';
const DATA_URL     = `${ORIGIN}/ai-academy/modules/courses-data.json`;
const DATA_CACHE_S = 3600;   // cache courses-data for 1 hour at the edge
const FALLBACK_IMG = `${ORIGIN}/og-image2.jpg`;
const SITE_NAME    = 'AESOP AI Academy';
const TWITTER_SITE = '@aesopacademy';

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Only intercept electives-hub with a ?course= query param
    if (
      !url.pathname.includes('electives-hub.html') ||
      !url.searchParams.has('course')
    ) {
      return fetch(request);
    }

    const courseId = url.searchParams.get('course') || '';

    // Basic sanity-check — course IDs are lowercase slugs
    if (!/^[\w-]{1,80}$/.test(courseId)) {
      return fetch(request);
    }

    // Fetch the origin HTML and course metadata in parallel
    const [pageResp, course] = await Promise.all([
      fetch(request),
      fetchCourse(courseId),
    ]);

    // If we couldn't find the course, pass through unchanged
    if (!course) return pageResp;

    const meta = buildMeta(courseId, course);

    return new HTMLRewriter()
      // Open Graph
      .on('meta[property="og:title"]',       { element: el => el.setAttribute('content', meta.title) })
      .on('meta[property="og:description"]', { element: el => el.setAttribute('content', meta.desc)  })
      .on('meta[property="og:image"]',       { element: el => el.setAttribute('content', meta.image) })
      .on('meta[property="og:url"]',         { element: el => el.setAttribute('content', meta.url)   })
      .on('meta[property="og:site_name"]',   { element: el => el.setAttribute('content', SITE_NAME)  })
      // Twitter Card
      .on('meta[name="twitter:title"]',       { element: el => el.setAttribute('content', meta.title) })
      .on('meta[name="twitter:description"]', { element: el => el.setAttribute('content', meta.desc)  })
      .on('meta[name="twitter:image"]',       { element: el => el.setAttribute('content', meta.image) })
      .on('meta[name="twitter:site"]',        { element: el => el.setAttribute('content', TWITTER_SITE) })
      // Canonical + page <title>
      .on('link[rel="canonical"]', { element: el => el.setAttribute('href', meta.url) })
      .on('title', {
        text(chunk) {
          if (chunk.text.trim()) {
            chunk.replace(meta.title, { html: false });
          }
        },
      })
      .transform(pageResp);
  },
};

// ── Fetch a single course from courses-data.json (edge-cached 1h) ─────
async function fetchCourse(courseId) {
  let resp;
  try {
    resp = await fetch(DATA_URL, {
      cf: {
        cacheTtl:        DATA_CACHE_S,
        cacheEverything: true,
      },
    });
  } catch {
    return null;
  }

  if (!resp.ok) return null;

  let data;
  try {
    data = await resp.json();
  } catch {
    return null;
  }

  return (data.courses || []).find(c => c.id === courseId) || null;
}

// ── Build course-specific meta values ────────────────────────────────
function buildMeta(courseId, course) {
  const name  = course.name || courseId;
  const title = `${name} — ${SITE_NAME}`;

  const rawDesc = course.description || '';
  const desc    = rawDesc.length > 300
    ? rawDesc.slice(0, 297) + '…'
    : rawDesc || `${name}. Part of AESOP AI Academy’s story-driven AI literacy curriculum.`;

  // Image generated by the GitHub Action at this exact path
  const image = `${ORIGIN}/assets/og/courses/${courseId}.png`;
  const url   = `${ORIGIN}/ai-academy/modules/electives-hub.html?course=${courseId}`;

  return { title, desc, image, url };
}
